/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MegaMenu: typeof import('primevue/megamenu')['default']
    Menu: typeof import('primevue/menu')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Password: typeof import('primevue/password')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
