export default [
    {
      path:'/admin',
      name: 'Admin',
      components:{
        app: () => import('@/admin/views/AdminLayout.vue')
      },
      children: [
        {
          path: '/admin',
          redirect: '/admin/dashboard'
        },
        {
          path:'/admin/dashboard',
          name:'Dashboard',
          components: {
            admin: () => import('@/admin/views/DashboardView.vue')
          }
        },
        {
          path:'/admin/perm',
          name:'Permissions',
          components: {
            admin: () => import('@/admin/views/PermManage.vue')
          },
          children:[
            {
              path:'/admin/perm',
              redirect: '/admin/perm/users'
            },
            {
              path:'/admin/perm/users',
              name:'PermUsers',
              components:{
                perm:()=>import('@/admin/components/perm/UserRoleManage.vue')
              }
            },
            {
              path:'/admin/perm/roles',
              name:'PermRoles',
              components:{
                perm:()=>import('@/admin/components/perm/RoleManage.vue')
              }
            },
            {
              path:'/admin/perm/permissions',
              name:'PermPermissions',
              components:{
                perm:()=>import('@/admin/components/perm/PermItem.vue')
              }
            }
          ]
        },
        {
          path:'/admin/problems',
          name:'ProblemAdmin',
          children:[
            {
              path:'/admin/problems',
              redirect: '/admin/problems/list'
            },
            {
              path:'/admin/problems/list',
              name:'AdminProblemList',
              components:{
                admin:()=>import('@/admin/components/problem/ProblemList.vue')
              }
            },
            {
              path:'/admin/problem/create',
              name:'AdminProblemCreate',
              components:{
                admin:()=>import('@/admin/components/problem/ProblemCreate.vue')
              }
            },
            {
              path:'/admin/problem/edit/:id',
              name:'AdminProblemDetail',
              components:{
                admin:()=>import('@/admin/components/problem/ProblemEditView.vue')
              },
              props:true
            },
            {
              path:'/admin/problem/testcases/:id',
              name:'AdminProblemTestCase',
              components:{
                admin:()=> import('@/admin/components/problem/ProblemTestCase.vue')
              },
              props:true
            },
            {
              path: '/admin/problems/tags',
              name: 'AdminProblemTags',
              components: {
                admin: () => import('@/admin/components/problem/TagList.vue')
              }
            },
            {
              path: '/admin/problems/import',
              name: 'AdminProblemImport',
              components: {
                admin: () => import('@/admin/components/problem/ProblemImport.vue')
              }
            },
            {
              path:'/admin/problems/remote-account',
              name:'AdminProblemRemoteAccount',
              components:{
                admin:()=>import('@/admin/components/remoteAccount/remoteAccountList.vue')
              }
            },
            {
              path:'/admin/problems/categories',
              name:'AdminProblemCategories',
              components:{
                admin:()=>import('@/admin/components/problem/ProblemCategory.vue')
              }
            }
          ]
        },
        {
          path:'/admin/homeworks',
          name:'ContestAdmin',
          children:[
            {
              path:'/admin/homeworks',
              redirect: '/admin/homeworks/list'
            },
            {
              path:'/admin/homeworks/list',
              name:'AdminHomeworkList',
              components:{
                admin:()=>import('@/admin/components/contest/HomeworkList.vue')
              }
            },
            {
              path:'/admin/homework/create/:copyId?',
              name:'AdminHomeworkCreate',
              components:{
                admin:()=>import('@/admin/components/contest/HomeworkCreate.vue')
              },
              props:true
            },
            {
              path:'/admin/homework/edit/:id',
              name:'AdminHomeworkEdit',
              components:{
                admin:()=>import('@/admin/components/contest/HomeworkEdit.vue')
              },
              props:true
            },
            {
              path:'/admin/homework/status/:id',
              name:'AdminHomeworkStatus',
              components:{
                admin:()=>import('@/admin/components/contest/HomeworkStatus.vue')
              }, 
              props:true
            }
          ]
        },
        {
          path:'/admin/users',
          name:'UserAdmin',
          children:[
            {
              path:'/admin/users',
              redirect: '/admin/users/list'
            },
            {
              path:'/admin/users/list',
              name:'AdminUserList',
              components:{
                admin:()=>import('@/admin/components/user/UserList.vue')
              }
            },
            {
              path:'/admin/users/import',
              name:'AdminUserImport',
              components:{
                admin:()=>import('@/admin/components/user/UserImport.vue')
              }
            },
            {
              path:'/admin/users/generate',
              name:'AdminUserGenerate',
              components:{
                admin:()=>import('@/admin/components/user/UserGenerate.vue')
              }
            },
            {
              path:'/admin/users/enable',
              name:'AdminUserEnable',
              components:{
                admin:()=>import('@/admin/components/user/EnableUser.vue')
              }
            },
            {
              path:'/admin/users/whitelist',
              name:'AdminUserWhitelist',
              components:{
                admin:()=>import('@/admin/components/user/UserIPWhitelist.vue')
              }
            },
            {
              path:'/admin/users/ip-import',
              name:'AdminUserWhitelistBatch',
              components:{
                admin:()=>import('@/admin/components/user/UserIPImportBatch.vue')
              }
            }
          ]
        },
        {
          path:'/admin/groups',
          name:'GroupAdmin',
          children:[
            {
              path:'/admin/groups',
              redirect: '/admin/groups/list'
            },
            {
              path:'/admin/groups/list',
              name:'AdminGroupList',
              components:{
                admin:()=>import('@/group/GroupManage.vue')
              }
            },
            {
              path:'/admin/group/create',
              name:'AdminGroupCreate',
              components:{
                admin:()=>import('@/group/GroupCreate.vue')
              }
            },
            {
              path:'/admin/group/edit/:id',
              name:'AdminGroupEdit',
              components:{
                admin:()=>import('@/group/GroupEdit.vue')
              },
              props:true
            }
          ]
        },
        {
          path:'/admin/rejudge',
          name:'AdminRejudge',
          components:{
            admin:()=>import('@/admin/components/judge/RejudgeView.vue')
          }
        },
        {
          path:'/admin/notices',
          name:'AdminNotices',
          children:[
            {
              path:'/admin/notices',
              redirect: '/admin/notices/list'
            },
            {
              path:'/admin/notices/list',
              name:'AdminNoticeList',
              components:{
                admin:()=>import('@/admin/components/notice/NoticeList.vue')
              },
              props:true
            }
          ],
        }
      ]
    }
];