export default [
    {
      path:'/admin',
      name: 'Admin',
      components:{
        app: () => import('@/admin/views/AdminLayout.vue')
      },
      children: [
        {
          path: '/admin',
          redirect: '/admin/dashboard'
        },
        {
          path:'/admin/dashboard',
          name:'Dashboard',
          components: {
            admin: () => import('@/admin/views/DashboardView.vue')
          }
        },
        {
          path:'/admin/perm',
          name:'Permissions',
          components: {
            admin: () => import('@/admin/views/PermManage.vue')
          },
          children:[
            {
              path:'/admin/perm',
              redirect: '/admin/perm/users'
            },
            {
              path:'/admin/perm/users',
              name:'PermUsers',
              components:{
                perm:()=>import('@/admin/components/perm/UserRoleManage.vue')
              }
            },
            {
              path:'/admin/perm/roles',
              name:'PermRoles',
              components:{
                perm:()=>import('@/admin/components/perm/RoleManage.vue')
              }
            },
            {
              path:'/admin/perm/permissions',
              name:'PermPermissions',
              components:{
                perm:()=>import('@/admin/components/perm/PermItem.vue')
              }
            }
          ]
        },
        {
          path:'/admin/problems',
          name:'ProblemAdmin',
          children:[
            {
              path:'/admin/problems',
              redirect: '/admin/problems/list'
            },
            {
              path:'/admin/problems/list',
              name:'AdminProblemList',
              components:{
                admin:()=>import('@/admin/components/problem/ProblemList.vue')
              }
            },
            {
              path:'/admin/problem/create',
              name:'AdminProblemCreate',
              components:{
                admin:()=>import('@/admin/components/problem/ProblemCreate.vue')
              }
            },
            {
              path:'/admin/problem/edit/:id',
              name:'AdminProblemDetail',
              components:{
                admin:()=>import('@/admin/components/problem/ProblemEditView.vue')
              },
              props:true
            },
            {
              path:'/admin/problem/testcases/:id',
              name:'AdminProblemTestCase',
              components:{
                admin:()=> import('@/admin/components/problem/ProblemTestCase.vue')
              },
              props:true
            }
          ]
        },
        {
          path:'/admin/homeworks',
          name:'ContestAdmin',
          children:[
            {
              path:'/admin/homeworks',
              redirect: '/admin/homeworks/list'
            },
            {
              path:'/admin/homeworks/list',
              name:'AdminHomeworkList',
              components:{
                admin:()=>import('@/admin/components/contest/HomeworkList.vue')
              }
            },
            {
              path:'/admin/homework/create',
              name:'AdminHomeworkCreate',
              components:{
                admin:()=>import('@/admin/components/contest/HomeworkCreate.vue')
              }
            },
            {
              path:'/admin/homework/edit/:id',
              name:'AdminHomeworkEdit',
              components:{
                admin:()=>import('@/admin/components/contest/HomeworkEdit.vue')
              },
              props:true
            },
            {
              path:'/admin/homework/status/:id',
              name:'AdminHomeworkStatus',
              components:{
                admin:()=>import('@/admin/components/contest/HomeworkStatus.vue')
              }, 
              props:true
            }
          ]
        },
        {
          path:'/admin/users',
          name:'UserAdmin',
          children:[
            {
              path:'/admin/users',
              redirect: '/admin/users/list'
            },
            {
              path:'/admin/users/list',
              name:'AdminUserList',
              components:{
                admin:()=>import('@/admin/components/user/UserList.vue')
              }
            },
            {
              path:'/admin/users/import',
              name:'AdminUserImport',
              components:{
                admin:()=>import('@/admin/components/user/UserImport.vue')
              }
            }
          ]
        }
      ]
    }
];